# Generated by Django 4.0.1 on 2022-03-07 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmodel',
            name='edited',
        ),
    ]
