# Generated by Django 4.0.1 on 2022-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfilmodel_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='perfilmodel',
            name='format_img',
        ),
        migrations.RemoveField(
            model_name='perfilmodel',
            name='url_img',
        ),
        migrations.AlterField(
            model_name='perfilmodel',
            name='name_img',
            field=models.ImageField(blank='', default='', upload_to='img_profile'),
        ),
    ]
