# Generated by Django 4.0.1 on 2022-02-24 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstComponent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fristmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
